apiVersion: apps/v1
kind: Deployment
metadata:
  name: project1-deployment
  namespace: project1
spec:
  selector:
    matchLabels:
      app: project1
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: project1
    spec:
      containers:
        - name: project1
          image: thomaspoignant/hello-world-rest-json
          ports:
            - name: project1
              containerPort: 8080
          resources:
            requests:
              cpu: 100m
              memory: 680Mi
            limits:
              cpu: 600m
              memory: 1800Mi
      terminationGracePeriodSeconds: 30
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: project1-deployment
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: project1-deployment
  minReplicas: 1
  maxReplicas: 4
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
---
apiVersion: v1
kind: Service
metadata:
  name: project1
  namespace: project1
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: project1
  type: NodePort
